# Generated by Django 6.0.1 on 2026-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(choices=[('comum', 'Comum'), ('vip', 'VIP')], max_length=20)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
