# Generated by Django 6.0.1 on 2026-04-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_nology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ip_cliente',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
